# Generated by Django 3.2.13 on 2023-01-17 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230103_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('m', 'Macho'), ('f', 'Fêmea')], max_length=1, verbose_name='Sexo do animal')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=64, verbose_name='Bairro')),
                ('endereco', models.CharField(max_length=128, verbose_name='Endereco')),
                ('complemento', models.CharField(max_length=128, verbose_name='Complemento')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF do tutor')),
                ('rg', models.CharField(max_length=10, verbose_name='Identidade')),
                ('dt_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('tipo_de_moradia', models.CharField(choices=[('Própria', 'Própria'), ('Alugada', 'Alugada')], max_length=7, verbose_name='Tipo de moradia')),
            ],
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
        migrations.AddField(
            model_name='animal',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipo'),
        ),
        migrations.AddField(
            model_name='animal',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tutor'),
        ),
    ]
