# Generated by Django 3.2.13 on 2023-01-17 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230117_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='castrado',
            field=models.BooleanField(default=False, verbose_name='Castrado'),
        ),
        migrations.CreateModel(
            name='Ave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anilha', models.CharField(max_length=64, verbose_name='Código da anilha')),
                ('especie', models.CharField(max_length=64, verbose_name='Espécie')),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.animal')),
            ],
        ),
    ]
