# Generated by Django 3.2.13 on 2023-01-17 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230117_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ave',
            old_name='id_animal',
            new_name='animal',
        ),
        migrations.AddField(
            model_name='animal',
            name='dt_inclusao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de inclusão'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='dt_inclusao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de inclusão'),
            preserve_default=False,
        ),
    ]
