# Generated by Django 3.2.13 on 2023-01-18 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
        ('core', '0005_auto_20230117_1409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Local',
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='animal',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autenticacao.tutor'),
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
