# Generated by Django 3.2.13 on 2023-01-23 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230120_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=64, null=True, verbose_name='Espécie')),
            ],
        ),
        migrations.RemoveField(
            model_name='ave',
            name='especie',
        ),
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(default=4, max_length=64, verbose_name='Espécie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='especie',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='core.especie'),
            preserve_default=False,
        ),
    ]
