# Generated by Django 3.2.13 on 2023-01-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230123_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especie',
            options={'ordering': ['nome']},
        ),
    ]
