# Generated by Django 3.2.13 on 2023-01-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_especie_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Nome/apelido'),
        ),
        migrations.DeleteModel(
            name='Especie',
        ),
    ]
