# Generated by Django 3.2.13 on 2023-01-24 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230124_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=64, null=True, verbose_name='Espécie')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='anilha',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Código da anilha'),
        ),
        migrations.DeleteModel(
            name='Ave',
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.especie'),
        ),
    ]
