# Generated by Django 3.2.13 on 2023-01-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230124_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especie',
            options={'ordering': ['nome_especie']},
        ),
        migrations.RenameField(
            model_name='especie',
            old_name='nome',
            new_name='nome_especie',
        ),
    ]
