# Generated by Django 3.2.13 on 2023-01-26 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20230124_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelagem', models.CharField(max_length=64, verbose_name='Pelagem')),
                ('dt_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de inclusão')),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.especie')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipo')),
            ],
        ),
    ]
