# Generated by Django 3.2.13 on 2023-01-31 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_info_extras_periodo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info_Extras',
            new_name='Informacoes_Extras',
        ),
    ]
