# Generated by Django 3.2.13 on 2023-01-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_info_extras_informacoes_extras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelagem', models.CharField(max_length=64, verbose_name='Pelagem')),
                ('idade', models.IntegerField(blank=True, null=True, verbose_name='Idade')),
                ('raca', models.CharField(blank=True, max_length=64, null=True, verbose_name='Raça')),
                ('sexo', models.CharField(choices=[('m', 'Macho'), ('f', 'Fêmea')], max_length=1, verbose_name='Sexo do animal')),
                ('castrado', models.BooleanField(default=False, verbose_name='Castrado')),
                ('vacinado', models.BooleanField(default=False, verbose_name='Vacinado')),
            ],
        ),
    ]
