# Generated by Django 3.2.13 on 2023-02-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_catalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
