# Generated by Django 3.2.13 on 2023-02-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_animal_animal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='errante',
            name='animal_image',
            field=models.ImageField(blank=True, null=True, upload_to='animal_errante/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_image',
            field=models.ImageField(blank=True, null=True, upload_to='animail_tutor/', verbose_name='N sei oq botar aqui'),
        ),
    ]
