# Generated by Django 3.2.13 on 2023-02-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20230202_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_image',
            field=models.ImageField(blank=True, null=True, upload_to='animal_tutor/', verbose_name='N sei oq botar aqui'),
        ),
    ]
