# Generated by Django 4.1.6 on 2023-02-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_animal_animal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='animal_image',
            field=models.ImageField(blank=True, null=True, upload_to='animal_tutor/', verbose_name='Foto do animal (opcional)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_image',
            field=models.ImageField(blank=True, null=True, upload_to='animal_tutor/', verbose_name='Foto do animal (opcional)'),
        ),
    ]
