# Generated by Django 3.2.13 on 2023-02-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_errante_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='sexo',
            field=models.CharField(choices=[('o', 'Macho'), ('a', 'Fêmea')], max_length=1, verbose_name='Sexo do animal'),
        ),
    ]
