# Generated by Django 4.1.6 on 2023-02-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_tokendesconto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrevistaPrevia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('bairro', models.CharField(max_length=64, verbose_name='Bairro')),
                ('endereco', models.CharField(max_length=128, verbose_name='Endereco')),
                ('quest_um', models.CharField(max_length=128, verbose_name='Porque você quer adotar um animal?')),
                ('quest_dois', models.BooleanField(default=False, verbose_name='Todas as pessoas que residem na casa gostam de animais?')),
                ('quest_tres', models.BooleanField(default=False, verbose_name='A residência que pretende acolher o animal tem o quintal completamente fechado?')),
                ('quest_quatro', models.BooleanField(default=False, verbose_name='Você tem consciência de que filhotes exigem cuidados especiais, pois podem chorar, destruir objetos da casa e precisagem de um tempo de adaptação?')),
                ('quest_cinco', models.BooleanField(default=False, verbose_name='Você tem condições de tratar o animal com ração de qualidade e água limpa diariamente?')),
                ('quest_seis', models.BooleanField(default=False, verbose_name='Você compromete-se com os cuidados veterinários necessários, além da vacinação anual do animal?')),
                ('quest_sete', models.BooleanField(default=False, verbose_name='Você tem consciência de que um animal vive cerca de 15 anos e que voc~e teá responsabilidade sobre sua vida durante todo esse tempo?')),
                ('quest_oito', models.BooleanField(default=False, verbose_name='Você tem plena consciência de que precisará higienizar, diariamente, o espaço onde o animal viverá, estando sujeito ao contato com suas necessidades fisiológicas?')),
                ('quest_nove', models.BooleanField(default=False, verbose_name='Você tem consciência de que, às vezes o animal poderá fazer suas necessidades em local indesejado?')),
                ('quest_dez', models.BooleanField(default=False, verbose_name='Você tem consciência de que, como fiel depositário do animal, ele não pode ser doado, vendido ou abandonado sob NENHUMA hipótese?')),
            ],
        ),
    ]
