# Generated by Django 4.1.6 on 2023-02-07 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_entrevistaprevia'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrevistaprevia',
            name='animal',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.catalogo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrevistaprevia',
            name='quest_cinco',
            field=models.BooleanField(choices=[(True, 'SIM'), (False, 'NÃO')], default=False, verbose_name='Você tem condições de tratar o animal com ração de qualidade e água limpa diariamente?'),
        ),
        migrations.AlterField(
            model_name='entrevistaprevia',
            name='quest_dez',
            field=models.BooleanField(choices=[(True, 'SIM'), (False, 'NÃO')], default=False, verbose_name='Você tem consciência de que, como fiel depositário do animal, ele não pode ser doado, vendido ou abandonado sob NENHUMA hipótese?'),
        ),
        migrations.AlterField(
            model_name='entrevistaprevia',
            name='quest_dois',
            field=models.BooleanField(choices=[(True, 'SIM'), (False, 'NÃO')], default=False, verbose_name='Todas as pessoas que residem na casa gostam de animais?'),
        ),
        migrations.AlterField(
            model_name='entrevistaprevia',
            name='quest_nove',
            field=models.BooleanField(choices=[(True, 'SIM'), (False, 'NÃO')], default=False, verbose_name='Você tem consciência de que, às vezes o animal poderá fazer suas necessidades em local indesejado?'),
        ),
        migrations.AlterField(
            model_name='entrevistaprevia',
            name='quest_oito',
            field=models.BooleanField(choices=[(True, 'SIM'), (False, 'NÃO')], default=False, verbose_name='Você tem plena consciência de que precisará higienizar, diariamente, o espaço onde o animal viverá, estando sujeito ao contato com suas necessidades fisiológicas?'),
        ),
        migrations.AlterField(
            model_name='entrevistaprevia',
            name='quest_quatro',
            field=models.BooleanField(choices=[(True, 'SIM'), (False, 'NÃO')], default=False, verbose_name='Você tem consciência de que filhotes exigem cuidados especiais, pois podem chorar, destruir objetos da casa e precisagem de um tempo de adaptação?'),
        ),
        migrations.AlterField(
            model_name='entrevistaprevia',
            name='quest_seis',
            field=models.BooleanField(choices=[(True, 'SIM'), (False, 'NÃO')], default=False, verbose_name='Você compromete-se com os cuidados veterinários necessários, além da vacinação anual do animal?'),
        ),
        migrations.AlterField(
            model_name='entrevistaprevia',
            name='quest_sete',
            field=models.BooleanField(choices=[(True, 'SIM'), (False, 'NÃO')], default=False, verbose_name='Você tem consciência de que um animal vive cerca de 15 anos e que voc~e teá responsabilidade sobre sua vida durante todo esse tempo?'),
        ),
        migrations.AlterField(
            model_name='entrevistaprevia',
            name='quest_tres',
            field=models.BooleanField(choices=[(True, 'SIM'), (False, 'NÃO')], default=False, verbose_name='A residência que pretende acolher o animal tem o quintal completamente fechado?'),
        ),
        migrations.AlterField(
            model_name='entrevistaprevia',
            name='quest_um',
            field=models.CharField(choices=[(True, 'SIM'), (False, 'NÃO')], max_length=128, verbose_name='Porque você quer adotar um animal?'),
        ),
    ]
