# Generated by Django 4.1.6 on 2023-02-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_tutor_alter_animal_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevistaprevia',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='entrevistaprevia',
            name='quest_um',
            field=models.CharField(max_length=128, verbose_name='Porque você quer adotar um animal?'),
        ),
    ]
