# Generated by Django 3.2.13 on 2023-01-18 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=64, verbose_name='Bairro')),
                ('endereco', models.CharField(max_length=128, verbose_name='Endereco')),
                ('complemento', models.CharField(max_length=128, verbose_name='Complemento')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF do tutor')),
                ('rg', models.CharField(max_length=10, verbose_name='Identidade')),
                ('telefone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone')),
                ('dt_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('tipo_de_moradia', models.CharField(choices=[('Própria', 'Própria'), ('Alugada', 'Alugada')], max_length=7, verbose_name='Tipo de moradia')),
                ('dt_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de inclusão')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.local')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
