# Generated by Django 3.2.13 on 2023-01-18 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='local',
        ),
        migrations.AddField(
            model_name='tutor',
            name='bairro',
            field=models.CharField(default=2, max_length=64, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='complemento',
            field=models.CharField(default=3, max_length=128, verbose_name='Complemento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='email',
            field=models.CharField(default=4, max_length=64, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='endereco',
            field=models.CharField(default=1, max_length=128, verbose_name='Endereco'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Local',
        ),
    ]
