# Generated by Django 3.2.13 on 2023-01-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_alter_tutor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
