# Generated by Django 3.2.13 on 2023-01-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_alter_tutor_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='rg',
        ),
    ]
