# Generated by Django 3.2.13 on 2023-02-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0005_remove_tutor_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
    ]
