# Generated by Django 4.1.6 on 2023-02-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0006_alter_tutor_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('dt_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('bairro', models.CharField(max_length=64, verbose_name='Bairro')),
                ('endereco', models.CharField(max_length=128, verbose_name='Endereco')),
                ('complemento', models.CharField(max_length=128, verbose_name='Complemento')),
                ('dt_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de inclusão')),
            ],
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user',
        ),
    ]
