# Generated by Django 4.1.6 on 2023-02-07 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0028_tutor_alter_animal_tutor'),
        ('autenticacao', '0007_pessoa_remove_tutor_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutor',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
